export const LOADER_START = "LOADER_START";
export const LOADER_STOP = "LOADER_STOP";
export const ALERT_MESSAGE = "ALERT_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const ITEM_LOADER_START = "ITEM_LOADER_START";
export const ITEM_LOADER_STOP = "ITEM_LOADER_STOP";

export const SAVE_USER_INFO = "SAVE_USER_INFO";
export const SAVE_FORM_DATA = "SAVE_FORM_DATA";
export const SAVE_USER_TOKEN = "SAVE_USER_TOKEN";
export const CLEAR_FORM_DATA = "CLEAR_FORM_DATA";
export const REMOVE_USER_INFO = "REMOVE_USER_INFO";
export const SAVE_LGA = "SAVE_LGA";
export const CLEAR_MORTGAGE = "CLEAR_MORTGAGE";
export const SAVE_MORTGAGE = "SAVE_MORTGAGE";

export const SAVE_CARDS = "SAVE_CARDS";
export const SAVE_PAYMENT_REF = "SAVE_PAYMENT_REF";
export const SAVE_USER_CONTRIBUTION = "SAVE_USER_CONTRIBUTION";
export const SAVE_USER_DEPOSIT = "SAVE_USER_DEPOSIT";
export const SAVE_USER_WITHDRAWAL = "SAVE_USER_WITHDRAWAL";
export const SAVE_BANKS = "SAVE_BANKS";
export const SAVE_CONTRACTUAL_INFO = "SAVE_CONTRACTUAL_INFO";
export const SAVE_ACCOUNT_NAME = "SAVE_ACCOUNT_NAME";
